import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  backBtn: { borderWidth: 1, borderColor: '#CACACA', width: 24,  height: 24, borderRadius: 4, cursor: 'pointer', position: 'absolute', left: 0,  alignItems: 'center', justifyContent: 'center' },
  container: { flex: 1,  padding: 24,  },
  headerText: { fontSize: 16, fontWeight: 'bold', justifyContent: 'center', textAlign: 'center' },
  progressPointActive: { width: 12, height: 12, borderRadius: 50, backgroundColor: '#31CECE' },
  progressPoint: { width: 12, height: 12, borderRadius: 50, backgroundColor: '#CACACA' },
  title: { fontSize: 32, fontWeight: 'bold', lineHeight: 42, letterSpacing: 1.5, color: '#222128'},
  input: {
    minHeight: 48,
    paddingHorizontal: 12,
    borderWidth: 0,
    borderRadius: 10,
    marginTop: 16,
    fontSize: 18,
    color: '#CACACA',
  },
  button: {
    backgroundColor: '#31CECE',
    paddingVertical: 14,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    maxWidth: 320,
  },
  buttonText: { color: 'white', fontSize: 16, fontWeight: '600' },
	addItemButton: {
		display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: 24,
    borderWidth: 1,
    borderColor: '#31CECE',
    borderRadius: 32, 
    borderStyle: 'dashed',
    width: '100%',
    height: 48,
    paddingHorizontal: 32,
    paddingVertical: 12,
    justifyContent: 'center',
    gap: 8
	},
  backText: { textAlign: 'center', marginTop: 10, color: '#999' },
	listContainer:{
		gap: 8,
		width: '100%',
		marginTop: 16,
	},
  addItemText: { 
		fontSize: 16,
    letterSpacing: 0.2,
    fontWeight: "500",
    fontFamily: "Roboto-Medium",
    color: "#31cece",
    textAlign: "left"
	 },
	 listItem: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		paddingVertical: 8,
		paddingHorizontal: 12,
		borderRadius: 16,
		borderWidth: 1,
		borderColor: '#DCE3E3',
		backgroundColor: '#FFF',	
		width: '100%',

	 },
	 listItemText: {
		flex: 1,
		fontSize: 20,
		letterSpacing: 0.3,
		fontWeight: "500",
		fontFamily: "Poppins-Medium",
		color: "#222128",
		textAlign: "left"
	 },
	 modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    padding: 24,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingBottom: 32,
		paddingHorizontal: 32,
		paddingTop: 44,
  },
  modalClose: {
    position: 'absolute',
    top: 16,
    right: 16,
  },
  modalTitle: {
    fontSize: 24,
		letterSpacing: 0.4,
		fontWeight: "500",
		fontFamily: "Poppins-Medium",
		color: "#000",
		textAlign: "left",
  },
  modalInput: {
    fontSize: 20,
		letterSpacing: 0.3,
		fontWeight: "500",
		fontFamily: "Poppins-Medium",
		color: "#cacaca",
		textAlign: "left",
		width: '100%',
		marginTop: 13,
		marginBottom: 20,
		paddingLeft: 8,
		borderLeftWidth: 2,
    borderLeftColor: '#31CECE',
  },
	modalTextArea: {
		fontSize: 20,
		letterSpacing: 0.3,
		fontWeight: "500",
		fontFamily: "Poppins-Medium",
		color: "#cacaca",
		textAlign: "left",
		width: '100%',
		minHeight: 160,
		textAlignVertical: 'top',
		marginTop: 13,
		paddingLeft: 8,
		borderLeftWidth: 2,
    borderLeftColor: '#31CECE',
	},
  modalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: 20,
		gap: 8
  },
	cancelButton: {
		flex: 1,
		borderRadius: 32,
		width: "100%",
		height: 48,
		overflow: "hidden",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: 32,
		paddingVertical: 12
	},
	addButton: {
		flex: 1,
		borderRadius: 32,
		backgroundColor: "#31cece",
		width: "100%",
		height: 48,
		overflow: "hidden",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: 32,
		paddingVertical: 12
	},
	buttonTextCancel: {
		fontSize: 16,
		letterSpacing: 0.2,
		fontWeight: "500",
		fontFamily: "Roboto-Medium",
		color: "#222128",
		textAlign: "left"
	},
	buttonTextAdd: {
		fontSize: 16,
		letterSpacing: 0.2,
		fontWeight: "500",
		fontFamily: "Roboto-Medium",
		color: "#fff",
		textAlign: "left"
	}
});